//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace banhang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Danhmuc_SP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Danhmuc_SP()
        {
            this.Don_Hangg = new HashSet<Don_Hangg>();
        }
    
        public string MaSP { get; set; }
        public string Ten_SP { get; set; }
        public string Gia_SP { get; set; }
    
        public virtual San_Pham San_Pham { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Don_Hangg> Don_Hangg { get; set; }
    }
}
