//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace banhang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Khach_Hang
    {
        public string MaKH { get; set; }
        public string Ho_Ten { get; set; }
        public string Tai_Khoan { get; set; }
        public string Mat_Khau { get; set; }
        public string Dia_Chi { get; set; }
        public string Dien_Thoai { get; set; }
        public string Email { get; set; }
        public Nullable<byte> Trang_Thai { get; set; }
    
        public virtual Don_Hangg Don_Hangg { get; set; }
    }
}
