//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace banhang.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QL_BANHANGEntities : DbContext
    {
        public QL_BANHANGEntities()
            : base("name=QL_BANHANGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Danhmuc_SP> Danhmuc_SP { get; set; }
        public virtual DbSet<Don_Hangg> Don_Hangg { get; set; }
        public virtual DbSet<Khach_Hang> Khach_Hang { get; set; }
        public virtual DbSet<Quan_Tri> Quan_Tri { get; set; }
        public virtual DbSet<San_Pham> San_Pham { get; set; }
    }
}
