//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace banhang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class San_Pham
    {
        public string MaSP { get; set; }
        public string Ten_SP { get; set; }
        public string Loai_SP { get; set; }
        public string Nam_SX { get; set; }
        public Nullable<byte> Trang_Thai { get; set; }
    
        public virtual Danhmuc_SP Danhmuc_SP { get; set; }
    }
}
